# Operating System
import os

# Colors
from colorama import Fore

# Set password
os.system('cls' if os.name == 'nt' else 'clear')
pas=input(f"Set password: {Fore.GREEN}")
os.system('cls' if os.name == 'nt' else 'clear')

def wrong():
    os.system('cls' if os.name == 'nt' else 'clear')
    print(Fore.RED + "Wrong password, all data will be deleted.")
    input(f"press enter to delete and exit: {Fore.RESET}")

# Main-Menu
def mainmenu():
    print(Fore.LIGHTCYAN_EX + "")
    print("      _ ___ _  __ ")
    print("|\ | / \ | |_ (_  ")
    print("| \| \_/ | |_ __) ")
                  
    ewp=input(f"Password: {Fore.GREEN}")
    if ewp == pas:
        # Take notes
        os.system('cls' if os.name == 'nt' else 'clear')
        print(Fore.RESET + "Notes:                -(30 lines)-")
        n1=input("1.")
        n2=input("2.")
        n3=input("3.")
        n4=input("4.")
        n5=input("5.")
        n6=input("6.")
        n7=input("7.")
        n8=input("8.")
        n9=input("9.")
        n0=input("10.")
        n11=input("11.")
        n22=input("12.")
        n33=input("13.")
        n44=input("14.")
        n55=input("15.")
        n66=input("16.")
        n77=input("17.")
        n88=input("18.")
        n99=input("19.")
        n00=input("20.")
        n111=input("21.")
        n222=input("22.")
        n333=input("23.")
        n444=input("24.")
        n555=input("25.")
        n600=input("26.")
        n777=input("27.")
        n888=input("28.")
        n999=input("29.")
        n000=input("30.")
        def notes():
            print(n1)
            print(n2)
            print(n3)
            print(n4)
            print(n5)
            print(n6)
            print(n7)
            print(n8)
            print(n9)
            print(n0)
            print(n11)
            print(n22)
            print(n33)
            print(n44)
            print(n55)
            print(n66)
            print(n77)
            print(n88)
            print(n99)
            print(n00)
            print(n111)
            print(n222)
            print(n333)
            print(n444)
            print(n555)
            print(n600)
            print(n777)
            print(n888)
            print(n999)
            print(n000)
        def menu():
            # menu
            os.system('cls' if os.name == 'nt' else 'clear')
            ewp=input(Fore.RESET + "Password:")
            if ewp == pas:
                os.system('cls' if os.name == 'nt' else 'clear')
                print(Fore.LIGHTCYAN_EX + "(1)See notes")
                print("(2)Lock")
                print("(3)Write")
                print("(4)Save")
                print("(5)exit")
                fg=input("\n==>")
                if fg == "1":
                    notes()
                    input("press enter to lock: ")
                    os.system('cls' if os.name == 'nt' else 'clear')
                    menu()
                elif fg == "2":
                    os.system('cls' if os.name == 'nt' else 'clear')
                    menu()
                elif fg == "3":
                    os.system('cls' if os.name == 'nt' else 'clear')
                    mainmenu()
                elif fg == "4":
                    print(Fore.RED + "The file will not be encrypted, if you want it to be encrypted, you will need to encrypt it manually!")
                    print(Fore.RESET + "Encryption command on GNU/Linux: gpg -c --no-symkey-cache --cipher-algo AES256 (file name)")
                    print("\nThe file will be saved at: ")
                    os.system('cd' if os.name == 'nt' else 'pwd')
                    fln=input("\nFile name (it should end with .txt): ")
                    os.system(f"echo '{n1}' >> {fln}")
                    os.system(f"echo '{n2}' >> {fln}")
                    os.system(f"echo '{n3}' >> {fln}")
                    os.system(f"echo '{n4}' >> {fln}")
                    os.system(f"echo '{n5}' >> {fln}")
                    os.system(f"echo '{n6}' >> {fln}")
                    os.system(f"echo '{n7}' >> {fln}")
                    os.system(f"echo '{n8}' >> {fln}")
                    os.system(f"echo '{n9}' >> {fln}")
                    os.system(f"echo '{n0}' >> {fln}")
                    os.system(f"echo '{n11}' >> {fln}")
                    os.system(f"echo '{n22}' >> {fln}")
                    os.system(f"echo '{n33}' >> {fln}")
                    os.system(f"echo '{n44}' >> {fln}")
                    os.system(f"echo '{n55}' >> {fln}")
                    os.system(f"echo '{n66}' >> {fln}")
                    os.system(f"echo '{n77}' >> {fln}")
                    os.system(f"echo '{n88}' >> {fln}")
                    os.system(f"echo '{n99}' >> {fln}")
                    os.system(f"echo '{n00}' >> {fln}")
                    os.system(f"echo '{n111}' >> {fln}")
                    os.system(f"echo '{n222}' >> {fln}")
                    os.system(f"echo '{n333}' >> {fln}")
                    os.system(f"echo '{n444}' >> {fln}")
                    os.system(f"echo '{n555}' >> {fln}")
                    os.system(f"echo '{n600}' >> {fln}")
                    os.system(f"echo '{n777}' >> {fln}")
                    os.system(f"echo '{n888}' >> {fln}")
                    os.system(f"echo '{n999}' >> {fln}")
                    os.system(f"echo '{n000}' >> {fln}")
                    os.system('cls' if os.name == 'nt' else 'clear')
                    menu()
                
                elif fg == "5":
                    print(Fore.RESET + "")
                    os.system('cls' if os.name == 'nt' else 'clear')

            
            elif ewp != pas:
                wrong()

        menu()
        # wrong password
    elif ewp != pas:
        wrong()
mainmenu()